### ISSUE TITLE
Results Per Page selection resets after search parameter is changed

### ISSUE THREAD

**Issue by ferncabrera** [ferncabrera/open_ims#150]
After selecting to view say 30 results per page on the CCGTable component:

![image](https://github.com/ferncabrera/open_ims/assets/73137447/091f0573-92cb-4e82-a16d-921b042fe84f)

If you then go to search by parameter it resets back to 10 results per page:

![image](https://github.com/ferncabrera/open_ims/assets/73137447/77590e63-c871-446a-9f67-9dee812199d7)

 This may be intended functionality (since after filtering you would have less results per page) but I think it may make more sense to have the users previous selection honored until they either reset the page count or perhaps leave and come back? Let me know what your thought are on this @Polsander.

**Comment by Polsander** [comment]
@ferncabrera originally intended for it to work this way. ~quick explanation~

Search parameter can be an intensive feature, hence why if it changes it should be limited to 10 and only the first 10 results (i.e. first index). If the user decides to flip pages or change the table size, the original search parameter is still honored. 

However if you feel like you would like to keep the table size consistent on search parameter changes, that can be arranged. The reset to first index has to happen though.

Let me know what you think @ferncabrera .

**Comment by ferncabrera** [comment]
Makes sense to me - thanks for explaining. Let me close this.
