### ISSUE TITLE
Make Company Names for Vendor Mandatory And Make Mandatory Customer Columns

### ISSUE THREAD

**Issue by Polsander** [ferncabrera/open_ims#160]
This is a database migration issue. @ferncabrera This is up your league.

Vendor Company Name needs to be *unique* and mandatory.

These customer fields need to be mandatory (in my opinion):
Not sure if we want company name to also be unique here (maybe not).
![image](https://github.com/ferncabrera/open_ims/assets/77382000/9ddbfcb4-c1f0-4f0c-90f4-d6a2e3b41b90)

Will open another issue that tackles front-end validations for this.

**Comment by ferncabrera** [comment]
Have addressed this in the PR I will link to this issue.

Have made the CUSTOMER Company Name unique as well.
