### ISSUE TITLE
Customer Database Changes

### ISSUE THREAD

**Issue by Polsander** [ferncabrera/open_ims#176]
Need Name in shipping and billing fields.

Will need to update the read and edit screens if these changes are made.

**Comment by Polsander** [comment]
@ferncabrera This is a good issue to tackle soon. If you're looking for some front/back work you can take this. Otherwise I will get around to this eventually after implementing Create and Delete.

**Comment by ferncabrera** [comment]
Yes totally missed this as a requirement in original schema... good catch.

It is a 2 line fix (or at least should be lol). I'd suggest quickly reading lines 100-152 which is the how-to;
![image](https://github.com/ferncabrera/open_ims/assets/73137447/b491e85d-30c0-4968-8bea-8f77f3029ff1)

But all you should need todo is goto the file:
`common/utils/migration-job/migrations/sqls/20230814020356-db-initialization-up.sql`

And then you'll just need to find the tables you want to update (in this case I think you want the vendor_addresses and customer _addresses tables):
![image](https://github.com/ferncabrera/open_ims/assets/73137447/38ecd46a-708b-4751-86ed-3eda0c8d224c)
And then just add the new attributes to those tables 😄 

You can confirm changes via successful logs, and in PGAdmin (The section on how to use that is below. You can view your table schemas there).

Then, in that same SQL file, youll probably need to update the section of the script that inserts the DUMMY data into the DB:
![image](https://github.com/ferncabrera/open_ims/assets/73137447/cd62e36f-b3e2-474a-81a2-9de5517df964)
Give them all names!

**Comment by Polsander** [comment]
Changes are done. Thanks for the info Fernando. Closing this issue.
