### ISSUE TITLE
Support Filter Search for Date

### ISSUE THREAD

**Issue by Polsander** [ferncabrera/open_ims#177]
Need date support for the invoice table on the read screen for customers.
Assigning to @ferncabrera , let me know if this is ok.

**Comment by ferncabrera** [comment]
Yeah we should probably standardize this, thanks for opening the ticket! Im not really sure I used too much of standard for the dashboard queries lol but I will make sure I get some sort of re-useable function going. We can even look into parsing the dates directly from postrges with the node-pg package we are using I read in the docs sometime ago...

**Comment by Polsander** [comment]
@ferncabrera My specific issue is fixed. Adding backlog label again.
Fix will come in as soon as this branch is merged: https://github.com/ferncabrera/open_ims/tree/table-landing-page

Also we need to talk about support for date filter search in the future. Whether we want it in mvp1 or mvp2.

**Comment by Polsander** [comment]
Date support actively being reviewed, confirmed and worked on. Closing this issue.
