### ISSUE TITLE
Styling changes for read and edit customer views

### ISSUE THREAD

**Issue by ferncabrera** [ferncabrera/open_ims#192]
Small styling changes required:

Needs to have grey-ish header/attribute title:
![image](https://github.com/ferncabrera/open_ims/assets/73137447/479572a4-5668-4493-b5e9-366004dd2afa)

Needs to have more spacing between rows:
![image](https://github.com/ferncabrera/open_ims/assets/73137447/2ce9a61c-06d0-4376-9c83-22db3d6f173b)

Just making sure the above panels have the same styling as the one below, screenshotted from Figma:
![image](https://github.com/ferncabrera/open_ims/assets/73137447/c271a35a-4025-4227-9905-22c5cd154f4b)

**Comment by Polsander** [comment]
@ferncabrera unsure what you mean by your first point needing a grey-ish header/attribute title.
![image](https://github.com/ferncabrera/open_ims/assets/77382000/442eae11-e9c1-40c2-8a35-c1bc7ab78116)

This is how it looks like for me ^
I am pretty sure the colour code is the same as is in the figma.

Will address the second point however and create more spacing on the read screen.

**Comment by Polsander** [comment]
@ferncabrera If you meant the grey-ish header that appears over the table and read screen, that's been added :)
