### ISSUE TITLE
Search Filter Discussion

### ISSUE THREAD

**Issue by Polsander** [ferncabrera/open_ims#195]
How are we going to manage search filters that go across 2 different tables?
One generic programmed search bar won't do.  I suggest having a drop down to add multiple search filters for specific cases, as well as a date picker. I will add a plethora of issues for each individual case.

Let me know if there is a different method you'd like to use Fernando that is alternative to the one I proposed. @ferncabrera 

Proposition is to have multiple filter buttons that select and specifically filter based on the required type of data we are looking for (i.e. name, location, phone-number, etc.) . Rather than have a single search variable.

**Comment by ferncabrera** [comment]
@Polsander This sounds good for sure. I like the idea of being able to select the search term. That way we can also just re-use the component and hide anything we cant filter by on some pages. Makes sense to me!

**Comment by Polsander** [comment]
Ok will leave this up for a few days for reference. Once the search filters will be worked on, this issue can be closed.
