### ISSUE TITLE
TS-Config Test Changes

### ISSUE THREAD

**Issue by Polsander** [ferncabrera/open_ims#21]
As our app grows (front-end and back-end) so will our files. Recompiling on hot reload will get laggy and needs to be managed in TS configurations.

![image](https://github.com/ferncabrera/open_ims/assets/77382000/41659e7c-3de6-4011-80d8-186c2b67d482)

Will use this image as reference for what could be done and might use a bit of testing.
This issue isn't guaranteed to have changes, but is primarily to see what works and what doesn't. If nothing works, we leave the configurations as is.

This issue is not a priority and will be probably resolved mid August.

**Comment by ferncabrera** [comment]
> As our app grows (front-end and back-end) so will our files. Recompiling on hot reload will get laggy and needs to be managed in TS configurations.
> 
> ![image](https://user-images.githubusercontent.com/77382000/256142509-41659e7c-3de6-4011-80d8-186c2b67d482.png)
> 
> Will use this image as reference for what could be done and might use a bit of testing. This issue isn't guaranteed to have changes, but is primarily to see what works and what doesn't. If nothing works, we leave the configurations as is.
> 
> This issue is not a priority and will be probably resolved mid August.

@Polsander Thanks for noting this down- Am wondering if you could also double check/clean up/familiarize yourself with the current pattern I use to track files using Skaffold for our client service. In the skaffold.yaml file at the root of our repo, you'll see a sync: manual list:

<img width="305" alt="image" src="https://github.com/ferncabrera/open_ims/assets/73137447/3eadfef7-ea00-4720-aae0-e2520bf81698">

If a file belongs to/matches any of the selectors then Skaffold will refresh the build. I initially made it and sort of guessed, you would know much better what Skaffold should be tracking changes for.

Let me know if you have any questions, you can read on the manual sync here: [Skaffold manual link](https://skaffold.dev/docs/filesync/#manual-sync-mode)

**Comment by Polsander** [comment]
I am closing this issue since I don't think any massive TS configurations need to be made. I also looked at the skaffold.yaml file @ferncabrera . Your comment makes sense to me. Don't see any additional standalone changes that need to be done. There might be some minor changes to have debugging work in the back-end, but I am not entirely sure if any changes here are necessary.
