### ISSUE TITLE
Login Page Implementation (Landing) - Styles - Design Libraries

### ISSUE THREAD

**Issue by Polsander** [ferncabrera/open_ims#22]
Basically a 3 in 1 ticket/issue.

**Requirements**
- Set up a global styles architecture that offers global classes, colours, and variables in scss that can be used anywhere throughout the app. Utilize wrappers so that future library packages do not interfere.
- Choose and implement front-end libraries to make development easier. (i.e. bootstrap v5 , semantic-ui-react, etc.) May need one for general styling and another for readily available components.
- Create style overrides that meet our designs for certain components that stem from libraries that are impacted by our global wrapper.
- Implement the landing page (Login page) as per Kelly's beautiful figma

**Edit 2023/07/28**
I will finish all authentication related pages. This ticket is solely focusing on getting the design implementation done.
Registration Page, Forgot password Modal will also be completed once this issue closes.

A separate issue will open for sending data since back-end integration work is needed as well.

**Figma for reference**
https://www.figma.com/file/LzQ0oUTimkNupQm1U7z3dG/open-ims?type=design&node-id=83%3A43&mode=design&t=lMxKwaRKjEeTFDwW-1

**Comment by ferncabrera** [comment]
@Polsander Not sure if you've ever used react-icons but that lib basically has all icons you would ever need lol (it bundles bootstrap-icons, ant design icons etc.) in an npm package. Would like to use that for all our icons, I think it is quite light as well.

**Comment by Polsander** [comment]
> @Polsander Not sure if you've ever used react-icons but that lib basically has all icons you would ever need lol (it bundles bootstrap-icons, ant design icons etc.) in an npm package. Would like to use that for all our icons, I think it is quite light as well.

Great idea! I always struggle with choosing an icon library haha.
