### ISSUE TITLE
UI side navigation redesign

### ISSUE THREAD

**Issue by kellygibson** [ferncabrera/open_ims#24]
<img width="1439" alt="Screenshot 2023-07-26 at 8 11 19 PM" src="https://github.com/ferncabrera/open_ims/assets/139164128/3adedf17-1654-4926-94d2-a3984b23d5ec">
UI for side menu navigation should be modified. 
- looks dated 
- should match dashboard better
- can improve icons & font

**Comment by kellygibson** [comment]
![Screenshot 2023-07-27 at 3 14 48 PM](https://github.com/ferncabrera/open_ims/assets/139164128/b5824263-a542-4955-8fc8-56dd3d882dba)
Better, not ready to be done yet though.

**Comment by Polsander** [comment]
This issue is done. Closing.
