### ISSUE TITLE
Add customization to home dashboard

### ISSUE THREAD

**Issue by kellygibson** [ferncabrera/open_ims#25]
Add features for customizing widgets displayed on dashboard.

**Comment by Polsander** [comment]
@kellygibson What is the current status on the widget designs?

**Comment by ferncabrera** [comment]
@Polsander have assigned this to us since Kelly has rolled off the project

**Comment by ferncabrera** [comment]
Since we are using Grafana now, this is now totally possible!!!

But now more so falls under what sort of access we are allowing the differing types of users across the org.
