### ISSUE TITLE
Front-end Form Validations - Design

### ISSUE THREAD

**Issue by Polsander** [ferncabrera/open_ims#32]
Hi @kellygibson , I am opening this issue since I remembered last night one thing we are missing.

We need validations for our fields. I can implement these but I need a design to go off on.
I know we have an error box below when the user tries to submit data that can show whether the form was valid or not, but that is generally reserved as a response the back-end sends. We can double our security and make UX a lot better for the user by showing whether the form they're filling out is valid or not in real time before they ever hit the submit or sign up button.

How do we want to show a field is invalid? (email missing @, password too short, special characters required, etc.)
We could have text like "password requires at least one special character !@#$%^&* " that displays under the field with a red border outline or something along the lines of that.

Do we want to show a success or checkmark is a field is appropriately added (i.e. valid password, valid email, etc.) once the user corrects it, or do we want to just remove the error highlighted?

Also keep in mind that every field selected has a secondary-blue box shadow when selected. Our choice if we want to keep it, remove it, or change it to red when the user selects a field that was previously shown an error (not validated).

some common validations to account for:
- Password (characters, length, capitalization)
- Email (valid email format, no duplicates)
- name (first and last, no special characters, length)

Not super high priority, but will be needing this as we create more forms and fields that allow user input.

**Comment by kellygibson** [comment]
gotcha I'm on it!

**Comment by ferncabrera** [comment]
@Polsander this is a great point - and actually since @kellygibson is handling database architecture it should be possible (and a little easier) to sanitize the entry of data across our website by restricting what type of data can be:

- Entered in the UI by a user and accepted into a form (client-side data validation done in Figma)
- Server-side API data-sanitization (done in our express APIs accepting form-data)
- Is there some sort of postgres-level data validations? (am thinking like mongoose email fields @Polsander)

Can't risk getting hacked!

**Comment by Polsander** [comment]
> @Polsander this is a great point - and actually since @kellygibson is handling database architecture it should be possible (and a little easier) to sanitize the entry of data across our website by restricting what type of data can be:
> 
> * Entered in the UI by a user and accepted into a form (client-side data validation done in Figma)
> * Server-side API data-sanitization (done in our express APIs accepting form-data)
> * Is there some sort of postgres-level data validations? (am thinking like mongoose email fields @Polsander)
> 
> Can't risk getting hacked!

@ferncabrera There seems to be a CHECK constraint we can use just to add that 3rd layer of security when creating table variables. See the link that's attached. https://www.w3schools.com/sql/sql_check.asp

For this issue, it's mostly just setting the criteria we are going to use. Then from here on out (on all future features), we just keep in mind and ensure we implement validations on front-end and backend. When we save or create new data in these tables, it'd be great to use this CHECK constraint.

**Comment by Polsander** [comment]
These basic validations are in place. Closing.
