### ISSUE TITLE
Find out how to cache docker builds in GitHub Actions pipeline

### ISSUE THREAD

**Issue by ferncabrera** [ferncabrera/open_ims#43]
We need to setup some way to cache our docker builds as the pr_acceptance_check workflow that runs when PR's are made to main can take a while.

For now, I am also adding another workflow that will just attempt to build the Dockerfiles (TS acceptance check) on every push. This way our team can know when a build will fail without needing to wait for the PR acceptance check job to complete (as Skaffold "hides" the build issues from us given that it is not actually re-building the app when we make updates).

**Comment by ferncabrera** [comment]
It seems like what we could do for now (other options like custom build scripts to cache directly from remote will overcomplicate things and is not necessary atm) is simply pull the last version of the image that was pushed before we try to build. That way we have the *near* same image on the GA Machine before it tries build and it can use those layers for its cache. This worked when testing on local so I will implement this but this ticket will remain open as we search for a more robust method to cache our builds.

**Comment by ferncabrera** [comment]
Well - it turns out you simply cannot pull and use the inline-image cache in our case since we have multi-stage builds and caching all layers requires the cache-to/destination to be anything but the local docker cache.

So looks like custom build scripts were the way to go - also since now we have more control over how our images are built before being used by skaffold perhaps we can start including some additional listeners to the containers @Polsander for debugging? using flags or env vars or something? not sure how that works i just console.log() 😄.

Anyways [here is the PR implementing the scripts](https://github.com/ferncabrera/open_ims/pull/107) enabling us to leverage the registry cache for our multi-stage dockerfiles that I merged in.

AFAIK and have tested nothing changes at all (regarding all other functionality) - although I was waiting on finishing this ticket before implementing the backend and fronend tests we have into our CI/CD pipeline LOL.

In the future we can look into perhaps making each of the scripts some .sh files that are passed the arguments so that the skaffold.yaml doesn't look so scary but for not it should be sufficient, I don't see us needing many more microservices for the time being anyways.... otherwise that could get very large very quick. Closing this as complete!

**Comment by Polsander** [comment]
Looks good @ferncabrera. Debugging back-end through node and through a kubernetes cluster on top of that is quite tricky. We need to prioritize our time finishing the app, so I don't want to put more effort into figuring that out. Unit tests and console.logs will have to do for now.
