### ISSUE TITLE
Backend Authentication

### ISSUE THREAD

**Issue by Polsander** [ferncabrera/open_ims#46]
Must be able to authenticate a user and create a session in the U.I.
Might involve additional front-end work for this to happen.

Added @ferncabrera as an assignee in case he would like to contribute to this and actively track his work.

**Requirements**
- Functional post API that creates a table and saves user information that is required.
- Create a session on the front-end with an expiration time. (As well as any seals to verify authenticity of token)
- Hash password and store it in DB
- Create another functional post API that allows user to log in and verifies hash.
- Create a third functional post API that allows user to successfully reset (update) their password.
- Validate in the back-end (wait for front-end first to complete this in separate issue).

**Notes**
Emails/users should not be duplicates, so ensure error handling is working appropriately.
Everything is a post request, avoid sending any sensitive data or info in the headers.

These routes don't need to be protected as everyone should be able to access them without any pre-existing authorization.

**Comment by ferncabrera** [comment]
Cool - Thanks for adding me to this. Let's touch base with Kelly and see if she can hand off/confirm the user Tables and any other we would need are complete.
