### ISSUE TITLE
Create database

### ISSUE THREAD

**Issue by ferncabrera** [ferncabrera/open_ims#5]
We need to initalize a Postgres DB service that is connected to our server.

**Comment by Polsander** [comment]
@ferncabrera Lucid Charts offers a way where it will write the SQL you need based on the diagram drawn. If you could research and find out how that's done it could save a lot of time.
Additionally I am not 100% confident I set the primary keys and foreign keys in the absolute correct way. We can get into a quick call and verify. (Your understanding based on what you learned in school would be useful here 😉 )

**Comment by ferncabrera** [comment]
Dope dude, will look into it, but this ticket for now is more concerned with just getting The actual database connected and some simple ping pong between it and the server. Will open another and mention your notes in its desc.

> @ferncabrera Lucid Charts offers a way where it will write the SQL you need based on the diagram drawn. If you could research and find out how that's done it could save a lot of time.
> 
> Additionally I am not 100% confident I set the primary keys and foreign keys in the absolute correct way. We can get into a quick call and verify. (Your understanding based on what you learned in school would be useful here 😉 )

**Comment by Polsander** [comment]
> Reference

@ferncabrera Awesome man, yeah I remember seeing this option but forgot how to obtain it. Before we run the code we may have to fix some keys based on how the table is defined. We can work on this after the database is created before we start making the tables.

**Comment by ferncabrera** [comment]
Just pushed my first crude implementation of a PostgreSQL instance built using the  latest Docker Hub image for the project. We managing our instance inside of our cluster ourself.

**Comment by ferncabrera** [comment]
The PR linked to this issue closes this ticket. It implemented a postgres database for use during local development. Although the PV that stores the data is wiped upon killing the Skaffold app, so there is still a lot of DB work TODO. Especially for prod.
