### ISSUE TITLE
Backend Validations - Show Backend Response on Front-end

### ISSUE THREAD

**Issue by Polsander** [ferncabrera/open_ims#64]
Work on this after the back-end auth is merged into main.

Leaving Assignees open to anyone who wants to do this.
I already have pre-existing regex on the front-end which can also be used on the back-end.
Use POSTMAN to ensure that these constraints are met.

**requirements**
- Ensure the back-end data meets our requirements for user registration and login. No blank submissions, and no harmful/wrong type data.
- Ensure an adequate message is shown and displayed on the front-end. Refer to Kelly's figma. Also see customError function in back-end to get an idea of how we are handling errors in express and sending them to the front-end.
- Create a loading spinner for when user submits data on the front-end as we wait for back-end response.

Any questions please ask.

**Comment by JosephFanous** [comment]
Will take :-)

**Comment by Polsander** [comment]
Resolved with the implementation of Recoil
