### ISSUE TITLE
Create Seeding API

### ISSUE THREAD

**Issue by JosephFanous** [ferncabrera/open_ims#69]
Should create a seeding API to populate the database with test data to help with dev work and testing.

Potential package which could help:
Faker.js - generates massive amounts of fake data in the browser and node.js.

**Comment by Polsander** [comment]
On a smaller scale, I might just make an administrator account when the tables get created. This will at least skip the process of tediously registering every time the app runs on dev.

**Comment by Polsander** [comment]
@ferncabrera this is a very old issue. Is it still necessary for us to have a seeding API?

**Comment by Polsander** [comment]
Closing this because we have pre-populated DB from migrations folder. No need to make an API, it's automatically part of app start-up on local.
